# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel', models.CharField(max_length=200)),
                ('ata_eta_mom', models.DateField()),
                ('ocean_del_terms', models.CharField(max_length=10)),
                ('bl_teu', models.IntegerField()),
                ('bl_feu', models.IntegerField()),
                ('cf_agent', models.CharField(max_length=20)),
                ('bl_number', models.CharField(max_length=50)),
                ('qty_disch_loaded', models.DecimalField(decimal_places=3, max_digits=10)),
                ('commodity', models.CharField(max_length=50)),
                ('pack', models.CharField(max_length=10)),
                ('recipient_country', models.CharField(max_length=20)),
                ('project_type', models.CharField(max_length=20)),
                ('sgs_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfUpload', models.DateField()),
                ('uploadedFile', models.FileField(upload_to='')),
            ],
        ),
    ]
